### ISSUE TITLE
다른 언어에도 적용 가능한지 궁금합니다.

### ISSUE THREAD

**Issue by ghost** [sgnlplabeling/nlp_labeling#21]
한국어 데이터셋으로 학습을 진행한 것으로 보이는데,
학습 데이터셋을 바꾸면 다른 언어에도 적용이 가능한지, 혹은 적용한 결과가 있는지 궁금합니다.

**Comment by KimGihwan** [comment]
학습이 가능합니다.
그러나 언어의 특성이 다르기 때문에 성능이 한국어 데이터셋보다 낮게 나올 수도 있습니다.
