### ISSUE TITLE
에러 관련 문의드립니다.

### ISSUE THREAD

**Issue by CHOJUNEHEE** [sgnlplabeling/nlp_labeling#22]
![image](https://user-images.githubusercontent.com/43003210/73906003-ac60f480-48e4-11ea-863a-2044ecfd122a.png)

딥러닝 NER을 돌려보려고 했는데, 위와 같은 오류가 발생합니다.
확인 후 수정 및 답변 부탁드립니다..

감사합니다.

**Comment by jisu3941** [comment]
네. 확인 후 수정하도록 하겠습니다.
감사합니다.

**Comment by KimGihwan** [comment]
<img width="593" alt="image" src="https://user-images.githubusercontent.com/37528240/76607381-3f7df180-6557-11ea-9784-2be63c0be1e6.png">

NER 부분 코드 수정 완료 했습니다.

감사합니다.

**Comment by KimGihwan** [comment]
<img width="593" alt="image" src="https://user-images.githubusercontent.com/37528240/76607535-72c08080-6557-11ea-9bfb-46e1c70f8b19.png">

NER 코드 수정 완료했습니다.

감사합니다.

**Comment by juae-kim** [comment]
코드가 수정되었기 때문에 해당 이슈는 close 하겠습니다.
