### ISSUE TITLE
학습 데이터 관련 문의

### ISSUE THREAD

**Issue by byhs** [sgnlplabeling/nlp_labeling#23]
다른 데이터를 이용해서 DP 모델을 학습시키고자 하는데, 학습 데이터 형식을 맞춰주기 위한 형태소 분석기는 어떤 걸 이용하면 되나요?

**Comment by boychaboy** [comment]
[여기](https://github.com/sgnlplabeling/nlp_labeling/blob/master/labeling_tool/deep-learning_based/DP/README.md)에 정보를 추가했으니 참고 부탁드립니다.

**Comment by boychaboy** [comment]
아래 두개의 형태소 분석기가 모두 필요합니다. 
1. pyKomoran v0.1.5 : 기본적인 워드 임베딩
2. etri 형태소 분석기 : etri에서 제공하는 pre-trained BERT

**Comment by boychaboy** [comment]
[여기](https://github.com/sgnlplabeling/nlp_labeling/blob/master/labeling_tool/deep-learning_based/DP/README.md) 맨 아랫 부분에 정보를 추가했으니 참고 부탁드립니다.

**Comment by byhs** [comment]
감사합니다.
