### ISSUE TITLE
 Speech Act requirements 설치 문제 문의

### ISSUE THREAD

**Issue by bosung** [sgnlplabeling/nlp_labeling#25]
안녕하세요, 

deep learning based 라벨링 툴에서 Speech Act관련 질문이 있습니다.

맨처음 README에 나와있는대로 pip install requirements.txt를 진행하면 다음과 같이 에러가 납니다.

$ pip install requirements.txt
Collecting requirements.txt
  ERROR: Could not find a version that satisfies the requirement requirements.txt (from versions: none)
ERROR: No matching distribution found for requirements.txt

requirements.txt를 따로 수정하지는 않았는데요,
혹시 라이브러리 version 문제인지 궁금해서요

**Comment by juae-kim** [comment]
안녕하세요, 

pip install -r requirements.txt 

명령어로 -r 옵션을 주셔야 requirements.txt에 있는 라이브러리들을 설치하실 수 있습니다. 
Readme에 오류가 있었던 것 같습니다. 수정하도록 하겠습니다. 

감사합니다.

**Comment by bosung** [comment]
-r 옵션 추가하니 잘 됩니다!

감사합니다 :)
