### ISSUE TITLE
DP에서 ELMO, BERT 사용 관련 질문입니다

### ISSUE THREAD

**Issue by uhniboogui** [sgnlplabeling/nlp_labeling#26]
안녕하세요,

DP 모델 관련 질문입니다. L2R 모델을 사용하셨는데, 만약에 모델의 input으로 ELMO와 BERT를 동시에 쓸 경우 두 모델의 output 결과를 concatenate 하는건가요?
그리고 BERT는 fintuning 한 것과 안한것의 차이가 얼마나 나는지 궁금합니다.

**Comment by boychaboy** [comment]
네 안녕하세요.
1. Concatenate한 것이 맞습니다. 
2. 약 2~3% 차이가 납니다.

**Comment by uhniboogui** [comment]
네 감사합니다! 👍
